name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: ["mccoderpy"]
body:
  - type: markdown
    attributes:
      value: Please fill in the fields below as accurately as possible to help us fix the bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you are trying and what is not working.
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: Branch used
      description: What branch of the library are you using?
      options:
        - main (stable)
        - developer
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        For the next 3 fields use the output of the `version` command
        ```ps
        # Windows
        py -m discord --version
        
        # Linux/macOS
        python3 -m discord --version # Replace 'python3' with the prefix of the Python version you are using
        ```
  - type: input
    id: python-version
    attributes:
      label: The Python verion you are using.
      placeholder: Python v3.8.10-final
    validations:
      required: true
  - type: input
    id: version-output
    attributes:
      label: What version (and release) of the library are you using
      placeholder: v2.0a294+gfb291a6
    validations:
      required: true
  - type: input
    id: system-info
    attributes:
      label: System info
      placeholder: Linux 5.4.0-126-generic
    validations:
      required: true
  - type: textarea
    id: traceback
    attributes:
      label: Full Traceback (Error)
      description: >
        Please copy and paste the complete traceback (error).
        This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: input
    id: contact-info
    attributes:
      label: Contact info
      description: Additional ways to contact you
      placeholder: mccuber04#2960 (Discord)
